name: Build ExpressLRS Bootloader
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Build all
      run: |
        platformio platform update
        mkdir -p ~/bootloaders
        platformio run
        mv binaries/*.bin ~/bootloaders
    - name: Store Artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: Bootloader-${{ env.BRANCH_NAME }}-${{ github.run_number }}
        path: ~/bootloaders/*.bin
      continue-on-error: true
